{
 "title": "vLLM Inference Dashboard",
 "description": "Monitoring vLLM Inference Server",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "panels": [
  { "title": "Generation", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Token Throughput",
   "type": "timeseries",
   "description": "Number of tokens processed per second",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "rate(vllm:prompt_tokens_total[$__rate_interval])",
     "legendFormat": "Prompt Tokens/Sec {{model_name}}"
    },
    {
     "expr": "rate(vllm:generation_tokens_total[$__rate_interval])",
     "legendFormat": "Generation Tokens/Sec {{model_name}}"
    }
   ]
  },
  {
   "title": "Scheduler State",
   "type": "timeseries",
   "description": "Number of requests in RUNNING, WAITING, and SWAPPED state",
   "gridPos": { "h": 15, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "vllm:num_requests_running", "legendFormat": "Num Running {{model_name}}" },
    { "expr": "vllm:num_requests_swapped", "legendFormat": "Num Swapped {{model_name}}" },
    { "expr": "vllm:num_requests_waiting", "legendFormat": "Num Waiting {{model_name}}" }
   ]
  },
  {
   "title": "Cache Utilization",
   "type": "timeseries",
   "description": "Percentage of used cache blocks by vLLM.",
   "gridPos": { "h": 15, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    { "expr": "vllm:gpu_cache_usage_perc", "legendFormat": "GPU Cache Usage {{model_name}}" },
    { "expr": "vllm:cpu_cache_usage_perc", "legendFormat": "CPU Cache Usage {{model_name}}" }
   ]
  },
  {
   "title": "Uptime/Status",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total Crashes",
     "type": "gauge",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "Crashes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expr": "increase(up[$__range])", "legendFormat": "{{job}}" }
     ]
    },
    {
     "title": "Uptime",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 11 },
     "targets": [
      { "expr": "avg_over_time(up[24h])", "legendFormat": "{{job}}" }
     ]
    }
   ]
  },
  {
   "title": "Latency",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 },
   "collapsed": true,
   "panels": [
    {
     "title": "E2E Request Latency",
     "type": "heatmap",
     "description": "End to end request latency measured in seconds.",
     "gridPos": { "h": 12, "w": 24, "x": 0, "y": 9 },
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum by(le, model_name) (rate(vllm:e2e_request_latency_seconds_bucket[$__rate_interval])))",
       "legendFormat": "P99 {{model_name}}"
      },
      {
       "expr": "histogram_quantile(0.95, sum by(le, model_name) (rate(vllm:e2e_request_latency_seconds_bucket[$__rate_interval])))",
       "legendFormat": "P95 {{model_name}}"
      },
      {
       "expr": "histogram_quantile(0.9, sum by(le, model_name) (rate(vllm:e2e_request_latency_seconds_bucket[$__rate_interval])))",
       "legendFormat": "P90 {{model_name}}"
      },
      {
       "expr": "histogram_quantile(0.5, sum by(le, model_name) (rate(vllm:e2e_request_latency_seconds_bucket[$__rate_interval])))",
       "legendFormat": "P50 {{model_name}}"
      },
      {
       "expr": "rate(vllm:e2e_request_latency_seconds_sum[$__rate_interval])\n/\nrate(vllm:e2e_request_latency_seconds_count[$__rate_interval])",
       "legendFormat": "Average {{model_name}}"
      }
     ]
    },
    {
     "title": "Time To First Token Latency",
     "type": "heatmap",
     "description": "P50, P90, P95, and P99 TTFT latency in seconds.",
     "gridPos": { "h": 15, "w": 12, "x": 0, "y": 21 },
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum by(le, model_name) (rate(vllm:time_to_first_token_seconds_bucket[$__rate_interval])))",
       "legendFormat": "P99 {{model_name}}"
      },
      {
       "expr": "histogram_quantile(0.95, sum by(le, model_name) (rate(vllm:time_to_first_token_seconds_bucket[$__rate_interval])))",
       "legendFormat": "P95 {{model_name}}"
      },
      {
       "expr": "histogram_quantile(0.9, sum by(le, model_name) (rate(vllm:time_to_first_token_seconds_bucket[$__rate_interval])))",
       "legendFormat": "P90 {{model_name}}"
      },
      {
       "expr": "histogram_quantile(0.5, sum by(le, model_name) (rate(vllm:time_to_first_token_seconds_bucket[$__rate_interval])))",
       "legendFormat": "P50 {{model_name}}"
      },
      {
       "expr": "rate(vllm:time_to_first_token_seconds_sum[$__rate_interval])\n/\nrate(vllm:time_to_first_token_seconds_count[$__rate_interval])",
       "legendFormat": "Average {{model_name}}"
      }
     ]
    },
    {
     "title": "Time Per Output Token Latency",
     "type": "heatmap",
     "description": "Inter token latency in seconds.",
     "gridPos": { "h": 15, "w": 12, "x": 12, "y": 21 },
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum by(le, model_name) (rate(vllm:time_per_output_token_seconds_bucket[$__rate_interval])))",
       "legendFormat": "P99 {{model_name}}"
      },
      {
       "expr": "histogram_quantile(0.95, sum by(le, model_name) (rate(vllm:time_per_output_token_seconds_bucket[$__rate_interval])))",
       "legendFormat": "P95 {{model_name}}"
      },
      {
       "expr": "histogram_quantile(0.9, sum by(le, model_name) (rate(vllm:time_per_output_token_seconds_bucket[$__rate_interval])))",
       "legendFormat": "P90 {{model_name}}"
      },
      {
       "expr": "histogram_quantile(0.5, sum by(le, model_name) (rate(vllm:time_per_output_token_seconds_bucket[$__rate_interval])))",
       "legendFormat": "P50 {{model_name}}"
      },
      {
       "expr": "rate(vllm:time_per_output_token_seconds_sum[$__rate_interval])\n/\nrate(vllm:time_per_output_token_seconds_count[$__rate_interval])",
       "legendFormat": "Mean {{model_name}}"
      }
     ]
    }
   ]
  }
 ]
}